steps:
- id: 'Executando docker-compose'
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f', 'docker-compose.yml', 'up', -d]

- id: 'Verificando se o container esta rodando'
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- id: 'Executando teste unitário'
  name: 'gcr.io/cloud-builders/go'
  args: ['test']
  env: ['GOPATH=/go/src']

# - id: "Build imagem Dockerfile"
#   name: 'gcr.io/cloud-builders/docker' 
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-golang:$SHORT_SHA', '-f', 'Dockerfile', '.']

# - id: "Push imagem Docker"
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/app-golang:$SHORT_SHA']